//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class filmUye
    {
        public int filmUyeID { get; set; }
        public int filmID { get; set; }
        public int uyeID { get; set; }
    
        public virtual film film { get; set; }
        public virtual uye uye { get; set; }
    }
}
