//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sinemaEntities2 : DbContext
    {
        public sinemaEntities2()
            : base("name=sinemaEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<film> film { get; set; }
        public virtual DbSet<filmUye> filmUye { get; set; }
        public virtual DbSet<haber> haber { get; set; }
        public virtual DbSet<resim> resim { get; set; }
        public virtual DbSet<uye> uye { get; set; }
        public virtual DbSet<yorum> yorum { get; set; }
        public virtual DbSet<slayder> slayder { get; set; }
        public virtual DbSet<video> video { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
    }
}
