//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yorum
    {
        public int yoruID { get; set; }
        public string ad { get; set; }
        public string icerik { get; set; }
        public Nullable<int> uyeID { get; set; }
        public Nullable<int> haberID { get; set; }
        public Nullable<int> filmID { get; set; }
    
        public virtual film film { get; set; }
        public virtual haber haber { get; set; }
        public virtual uye uye { get; set; }
    }
}
